#!/bin/bash

# creating new all_history_enriched.csv file with appropiate header ("day_of_week" column will be added)
awk -F"," -v OFS="," '{$5=$(date --date=$1 +%u) ;print $1, $5, $2, $3, $4}' all_history.csv > tmp.csv
sed 1i'"date","day_of_week","session_id","username","commands"' tmp.csv > all_history_enriched.csv

rm -f tmp.csv
echo "The enriched historical data has created into all_history_enriched.csv."
ls -al all_history_enriched.csv

